## YAML Template.
---
#driverDB: com.mysql.jdbc.Driver
#urlDB: jdbc:mysql://db4free.net:3307/baseerick?useSSL=false
driverDB: org.hsqldb.jdbc.JDBCDriver
urlDB: jdbc:hsqldb:mem:instituto
userDB: erick
passDB: P@ssw0rd13
#mailFrom: alumno1@iesquevedo.es
#smtpServer: smtp.gmail.com
#smtpPort: 587
#mailPass: alumnodam2
###passDB: clasesdaw